Repository Alexflames/GGLPlanet, pull requests merged in 2019-06, with the labels that each got.

#1 Updated .gitignore
  .gitignore
Labels: enhancement

#3 Added bullet collisions and updated the player collider
  Assets/Scripts/Characters/Enemies/Baddies/ExtremeBaddyProj.cs
  Assets/Scripts/Characters/Enemies/CollidingPlayers.cs
  Assets/Scripts/Characters/Enemies/LaserCubeLines.cs
  Assets/Scripts/Characters/Player/Projectiles/ProjectileLife.cs
  Assets/Scripts/Landscape/BackgroundClouds.cs
  Assets/_Prefabs/Character.prefab
  Assets/_Prefabs/EBprojectile.prefab
  Assets/_Scenes/Scene_RayHammer.unity
  Assets/_Scenes/Scene_RayHammer.unity.meta
  ProjectSettings/TagManager.asset
Labels: enhancement

#4 Attack manager
  Assets/Scripts/Characters/Enemies/Attack.cs
  Assets/Scripts/Characters/Enemies/Attack.cs.meta
  Assets/Scripts/Characters/Enemies/CuboidAttack.cs
  Assets/Scripts/Characters/Enemies/CuboidAttack.cs.meta
  Assets/Scripts/Characters/Enemies/CuboidAttackManager.cs
  Assets/Scripts/Characters/Enemies/CuboidAttackManager.cs.meta
  Assets/Scripts/Characters/Enemies/EmptyAttack.cs
  Assets/Scripts/Characters/Enemies/EmptyAttack.cs.meta
  Assets/Scripts/Characters/Enemies/LaserCubeLinesAttack.cs
  Assets/Scripts/Characters/Enemies/LaserCubeLinesAttack.cs.meta
  Assets/_Scenes/TestScene.unity
  Assets/_Scenes/TestScene.unity.meta
Labels: enhancement, good first issue

#6 Priority based choosing in the attack manager
  Assets/Scripts/Characters/Enemies/CuboidAttackManager.cs
  Assets/Scripts/Characters/Enemies/LaserCubeLinesAttack.cs
  Assets/Scripts/Characters/Player/Projectiles/PlayerShooting.cs
  Assets/_Scenes/TestScene.unity
Labels: enhancement

#9 Enemies movement controller
  Assets/Scripts/Characters/Enemies/Baddies/BaddyLogic.cs
  Assets/Scripts/Characters/Enemies/Cuboid.meta
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttackManager.cs
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttackManager.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/EmptyAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/EmptyAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/LaserCubeLinesAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/LaserCubeLinesAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/ScaryCuboidMoveController.cs
  Assets/Scripts/Characters/Enemies/Cuboid/ScaryCuboidMoveController.cs.meta
  Assets/Scripts/Characters/Enemies/LaserCubeLines.cs
  Assets/Scripts/Characters/Enemies/MoveController.cs
  Assets/Scripts/Characters/Enemies/MoveController.cs.meta
  Assets/Scripts/Characters/Enemies/NPCMovement.cs
  Assets/Scripts/Characters/Enemies/NPCMovement.cs.meta
  Assets/Scripts/Landscape/BackgroundClouds.cs
  Assets/_Prefabs/CloudsManager.prefab
  Assets/_Prefabs/CloudsManager.prefab.meta
  Assets/_Prefabs/CuboidTheCube.prefab
  Assets/_Scenes/FirstScene.unity
Labels: enhancement, good first issue

#10 Fixed the attack networking issue
  Assets/Scripts/Characters/Enemies/Baddies/BaddyLogic.cs
  Assets/Scripts/Characters/Enemies/Cuboid.meta
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttackManager.cs
  Assets/Scripts/Characters/Enemies/Cuboid/CuboidAttackManager.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/EmptyAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/EmptyAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/LaserCubeLinesAttack.cs
  Assets/Scripts/Characters/Enemies/Cuboid/LaserCubeLinesAttack.cs.meta
  Assets/Scripts/Characters/Enemies/Cuboid/ScaryCuboidMoveController.cs
  Assets/Scripts/Characters/Enemies/Cuboid/ScaryCuboidMoveController.cs.meta
  Assets/Scripts/Characters/Enemies/LaserCubeLines.cs
  Assets/Scripts/Characters/Enemies/MoveController.cs
  Assets/Scripts/Characters/Enemies/MoveController.cs.meta
  Assets/Scripts/Characters/Enemies/NPCMovement.cs
  Assets/Scripts/Characters/Enemies/NPCMovement.cs.meta
  Assets/Scripts/Landscape/BackgroundClouds.cs
  Assets/_Prefabs/CloudsManager.prefab
  Assets/_Prefabs/CloudsManager.prefab.meta
  Assets/_Prefabs/CuboidTheCube.prefab
  Assets/_Scenes/FirstScene.unity
  Assets/_Scenes/Scene_RayHammer.unity
Labels: bug

#11 Fixed the living sprites getting behind the laser grid and scene decorations
  Assets/_Prefabs/Character.prefab
  Assets/_Prefabs/CuboidTheCube.prefab
  ProjectSettings/TagManager.asset
Labels: bug
